paths:
  /auth/register:
    post:
      tags:
        - User
      summary: 회원가입
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 이메일
                  example: test@gmail.com
                name:
                  type: string
                  description: 실명
                  example: 홍길동
                nickname:
                  type: string
                  description: 닉네임
                  example: 길똥
                phone:
                  type: string
                  description: 핸드폰 번호
                  example: 010-1234-5678
                birth:
                  type: string
                  format: date
                  description: 생년월일
                  example: 2001-08-09
                password:
                  type: string
                  description: 비밀번호 (숫자, 소문자, 대문자를 1개이상, 6~20자리 이내)
                  example: Gildong0809!
                file:
                  type: string
                  format: binary
                  description: 프로필 이미지
      responses:
        "200":
          description: 회원 가입 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "Success!"
                  result:
                    type: object
                    properties:
                      email:
                        type: string
                      name:
                        type: string
                      nickname:
                        type: string
                      phone:
                        type: string
                      birth:
                        type: string
                      profile_image:
                        type: string
                      password:
                        type: string
                      point:
                        type: integer
                      premium:
                        type: boolean
                      status:
                        type: string
                      _id:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          example: MEMEBER4003
                        message:
                          type: string
                          example: "이미 존재하는 이메일입니다."

                  code:
                    type: integer
                    example: COMMON001
                  message:
                    type: string
                    example: "잘못된 요청입니다"
        "500":
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON000
                  message:
                    type: string
                    example: "서버 에러, 관리자에게 문의 바랍니다"
